global:
  resolve_timeout: 1m
  slack_api_url: '<insert-slack-hook>'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#odyssey-alerts'
    send_resolved: true
    title: '[{{ .Status | toUpper }}] {{ .Alerts | len }} Alert(s)'
    text: |-
      {{ range .Alerts }}
        ----------------------------------------------
        *Alert:* `{{ .Labels.alertname }}`
        *Description:* {{ .Annotations.description }}
        *Summary:* {{ .Annotations.summary }}
        *Labels*:
        {{ range .Labels.SortedPairs }}• {{ .Name }}: `{{ .Value }}`
        {{ end }}
      {{ end }}