global:
  resolve_timeout: 1m
  slack_api_url: '<insert-slack-hook>'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#odyssey-monitor'
    send_resolved: true