groups:
- name: default
  rules:
  - alert: AccountBalanceLow
    expr: |
      balance_account < 0.5
    for: 5m
    labels:
      severity: high
    annotations:
      summary: '{{ $labels.label }} account balance is too low ({{ $value }} ETH)'
      description: |-
        Account {{ $labels.label }} ({{ $labels.address }}) has a balance of {{ $value }} ETH, which is below 1 ETH threshold.
        Please top up this account.
  - alert: BlockNotIncrementing
    expr: |
      changes(current_block[5m]) == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Block number not incrementing"
      description: "Block number has been stuck for over 5 minutes."
  - alert: SequencerIsStuck
    expr: |
      nonce_gap > 0 and changes(nonce_gap[5m]) == 0 and changes(sequencer_nonce[5m]) == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Sequencer nonce not incrementing"
      description: "Sequencer nonce hasn't increased while there is a nonce gap of {{ $value }}"
  - alert: HealthCheckFailing
    expr: |
      up{job="health_monitor"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Health check endpoint is down"
      description: "Health check endpoint at {{ $labels.instance }} is not responding with HTTP 200"
# Uncomment the negating test alerts below if you want to verify slack hook works well when testing
  # - alert: TEST ALERT SequencerNonceChanging
  #   expr: |
  #     changes(sequencer_nonce[5m]) > 0
  #   for: 5m
  #   labels:
  #     severity: high
  #   annotations:
  #     summary: '{{ $labels.label }} test alert for local testing sequencer nonce is changing'
  #     description: |-
  #       THIS IS JUST A TEST ALERT FOR LOCAL TESTING
# Uncomment the negating test alerts below if you want to verify slack hook works well when testing
  # - alert: NEGATING TEST ALERT AccountBalanceLow
  #   expr: |
  #     balance_account > 0.5
  #   for: 5m
  #   labels:
  #     severity: high
  #   annotations:
  #     summary: '{{ $labels.label }} test alert for local testing: account balance is too low ({{ $value }} ETH)'
  #     description: |-
  #       THIS IS JUST A TEST ALERT FOR LOCAL TESTING
  #       Account {{ $labels.label }} ({{ $labels.address }}) has a balance of {{ $value }} ETH, which is below 0.5 ETH threshold.
  #       Please top up this account.